### ISSUE TITLE
Multiple thesaurus files

### ISSUE THREAD

**Issue by tcbtcb** [Ron89/thesaurus_query.vim#1]
Hello, I arrived here via the Stackoverflow conversation. As I said there, I'm interested in using other sources for the thesaurus file. If anyone who reads this knows of a good one that is available with a CC or copyleft license, please let me know. I can certainly work on formatting it and getting it ready for use with this (or another) vim plugin.

**Comment by Ron89** [comment]
Hmm, right. Having more than one thesaurus backend is what I had in mind when I started drafting this plugin. Basically, just assign your thesaurus query backend to `Thesaurus_Query_Handler.query_backend`, and make sure that once your `query_backend.query("word")` is called, a synonym list will be returned in format of layered list:

        [status, [def_0, [synonym_0, synonym_1, ...]],  [def_1, [synonym_0, synonym_1, ...]], ...]
    status:
        0: normal,  synonym found, list will be returned as 
        1: normal, synonym not found, return empty synonym list
        -1: unexpected result from query, return empty synonym list
    synonym list = [def, list wordlist]
        def('str'): definition the synonyms belong to
        wordlist = [synonym_0, synonym_1, ...]: list of words belonging to a same definition

**Comment by tcbtcb** [comment]
Super, thanks for the explanation. I will check into this and follow along to the extent of my ability.

**Comment by Ron89** [comment]
Alternative backend is finished. You may prioritize it over Online Routine by setting

    let g:thesaurus_query#use_local_thesaurus_source_as_primary = 1

Also, to make it work, you need to download `mthesaur.txt`, as described in `README.md`.

If you still think it is necessary to develop a new backend, take note that a change is made in my `Thesaurus_Query_Handler`. Now `query_backend` is a backend list, you may attach or insert the backend you create into the list. Returned structure remains the same.

**Comment by tcbtcb** [comment]
Thanks much for the information. I will take a look soon once I have some time to concentrate. Very impressed with how it works now.
