### ISSUE TITLE
Error when choosing empty synonym

### ISSUE THREAD

**Issue by nabsiddiqui** [Ron89/thesaurus_query.vim#10]
If the user decides not to change a synonym, you get "Invalid Input! Ending synonym replacing session without making changes."  I believe this is just a simple spacing issue.  If you press backspace and enter, it works as it should.

**Comment by Ron89** [comment]
That is strange. It worked correctly on both my Linux machine and my Mac... It prompt me invalid input when I press space. I mean, in my code the condition was if the input was empty or `None` then quit without warning...

Could you share with me your vim setup which you think might be relevant to the issue? Also, which plugin version are you using? Were you managing the plugin with plugin manager or installed it manually?

**Comment by nabsiddiqui** [comment]
It seemed to be a spacing issue in my remapping.  I think some whitespace got placed somewhere.  Sorry for the confusion, and thanks for your quick reply.
