### ISSUE TITLE
Add a backend for German

### ISSUE THREAD

**Issue by jceb** [Ron89/thesaurus_query.vim#12]
It would be handy to also have backend for German.

**Comment by Ron89** [comment]
Hey, sorry for the delay. I have made a German backend with [woxikon.de](http://synonyme.woxikon.de/synonyme). It doesn't have stemmer, so the plugin would have trouble with derivative form of words. Also, as it seems that woxikon tend to render very long list of synonyms, you might want to setup the `g:tq_truncation_on***` variables to use it sensibly.

German functionality, like Russian, is disabled by default. To enable it, add `'de'` to the list variable `g:tq_language`.

If you have further suggestions regarding to this functionality, feel free to tell me. :)

**Comment by jceb** [comment]
Thanks, it works well!
