### ISSUE TITLE
woxikon.de changed Design

### ISSUE THREAD

**Issue by dunkla** [Ron89/thesaurus_query.vim#16]
Because woxikon.de changed their design, the backend isn't working anymore. This needs fixing, or maybe we should switch to an api supported backend for german language, see #15.

**Comment by Ron89** [comment]
Noted. I'll fix it by end of this week. :)

**Comment by Ron89** [comment]
Plugin updated,  commit 89c990a should have resolved your issue. 
Sorry for the delay. :)

**Comment by Ron89** [comment]
@dunkla if the problem is solved for you too, could you close the issue?

**Comment by dunkla** [comment]
@Ron89 Sorry for the delay, your fix works as intended.
