### ISSUE TITLE
New Thesaurus source: YARN -- WordNet-like machine-readable thesaurus for the Russian language

### ISSUE THREAD

**Issue by petRUShka** [Ron89/thesaurus_query.vim#18]
There is a crowdsourcing project: https://russianword.net/en/

Quotation:

> The Yet Another RussNet (YARN) project was initiated in 2013 and aims at creating a large open WordNet-like machine-readable thesaurus for the Russian language through crowdsourcing. The project objectives include creating the thesaurus, developing free and libré open source software to operate with it, designing the necessary data schemes and models, writing technical and user documentation. The thesaurus is available under the CC BY-SA license.

There is a public HTTP API (unfortunately documentation I've found only in Russian): https://nlpub.ru/YARN/API

Google translate of that documentation (which is quite readable): https://translate.google.com/translate?hl=ru&sl=ru&tl=en&u=https%3A%2F%2Fnlpub.ru%2FYARN%2FAPI

It should be very good and stable solution for Russian language.

**Comment by petRUShka** [comment]
P.S. It is also accessible downloadable CSV or XML files with thesaurus, format and links on that small  wiki page (in English): https://nlpub.ru/YARN/Format

**Comment by Ron89** [comment]
Took a look of the links you shared. I can't figure how its online API works, and the git repository is last updated years back. But the offline source  http://russianword.net/yarn-synsets.csv looks very workable. I'll come up with something next week.

Thanks for the suggestion.

**Comment by Ron89** [comment]
Sorry for the long delay. As of commit 9124403, `yarn-synsets.csv` based thesaurus is finished and placed in higher priority than `jeck_ru`. To use, please download `yarn-synsets.csv` into folder `~/.vim/thesaurus`. If it works well for you, please mark this issue as resolved.

**Comment by Ron89** [comment]
Long time no feedback. Now consider this issue resolved.
