### ISSUE TITLE
Bad var name g:tq_yarn-synsets_file

### ISSUE THREAD

**Issue by vbauerster** [Ron89/thesaurus_query.vim#21]
Having this line in neovim config
`let g:tq_yarn-synsets_file = "~/.config/nvim/thesaurus/yarn-synsets.csv"`
causing following errors:
```
E121: Undefined variable: g:tq_yarn
E488: Trailing characters
Press ENTER or type command to continue
```
Maybe it worth rename `g:tq_yarn-synsets_file` to `g:tq_yarn_synsets_file`?
There is no problems with `g:tq_mthesaur_file` for example.

**Comment by Ron89** [comment]
Thanks for pointing out the issue. Suggestion is now adopted in commit d894a9b. Old variable name, as you pointed out, is impossible to be used by Vim environment, so I simply discarded it.

Try it out?

**Comment by vbauerster** [comment]
Confirm, it is ok now. Thank you!

**Comment by Ron89** [comment]
OK, closing issue now. :)
