### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bearcatsandor** [Ron89/thesaurus_query.vim#22]
Yeah, it's not a bug report or a feature request.  There's no "like" button on github so i have to do this the old fashioned way.

Thank you for an awesome plugin, that is incredibly useful and has become a daily driver for me!  I'm recommending it here and there.

I suppose "keep developing this, and keep being awesome" would be the feature request.

**Comment by Ron89** [comment]
Glad you like it~

I didn't have much time of late, so although I do have some ideas in mind to improve the tool, like
* auto-download offline source when cannot find it in user defined location
* add antonym query support for suitable backends
But I don't think I have the time to implement them in the following months. Hopefully within half a year I can wrap-up my student life properly and then I can work on it again. But before that I think the most I can do is bug fixings...

Still, thanks for your encouragement. I'll try to come back to it sooner. :)
