### ISSUE TITLE
mapping already exists for <leader>cs

### ISSUE THREAD

**Issue by sadid** [Ron89/thesaurus_query.vim#23]
I've set:
``` vimscript
nnoremap <leader>ct :ThesaurusQueryReplaceCurrentWord<CR>
vnoremap <leader>ct y:ThesaurusQueryReplace <C-r>"<CR>
```
in my `.vimrc` file.  But I get the above error when running vim. 

I even tried this:
``` vimscript
nnoremap <leader>ct :ThesaurusQueryReplaceCurrentWord<CR>
vnoremap <leader>ct "ky:ThesaurusQueryReplace <C-r>k<CR>
nnoremap <leader>ct :ThesaurusQueryReplaceCurrentWord<CR>
vnoremap <leader>ct "ky:ThesaurusQueryReplace <C-r>k<CR>
```
or other scenarios. I only be able to fix this problem with changing the same definitions in the `~/.vim/plugged/thesaurus_query.vim/plugin/thesaurus_query.vim` file which is not a robust fix. 
``` vimscript
if g:tq_map_keys
    nnoremap <unique><silent> <Leader>ct :ThesaurusQueryReplaceCurrentWord<CR>
    vnoremap <unique><silent> <Leader>ct "ky:ThesaurusQueryReplace <C-r>k<CR>
    nnoremap <silent> <LocalLeader>ct :ThesaurusQueryReplaceCurrentWord<CR>
    vnoremap <silent> <LocalLeader>ct "ky:ThesaurusQueryReplace <C-r>k<CR>
endif

```

I'm using vim-8.0.1176-1

**Comment by Ron89** [comment]
In this case, you can `let g:tq_map_keys=0` in your vimrc file and add your own key mappings in it. This way, the plugin won't setup default key mapping. Do you think this is good enough?

**Comment by sadid** [comment]
@Ron89 Good, Thanks.  Now I can go without modifying the source. But I can't use my custom keybinding as well and I've to go with `:The<Tab>` which is Ok but not ideal.  I might have missed something. Here is my .vimrc:

``` vimscript
let g:tq_map_keys=0
nnoremap <leader>ct :ThesaurusQueryReplaceCurrentWord<CR>
vnoremap <leader>ct y:ThesaurusQueryReplace <C-r>"<CR>
```

**Comment by Ron89** [comment]
This is strange... The mappings should work. Have you tried to see the
mappings of your current buffer and see if it is actually mapped or
override by something else? You can do so by
`:map`
And if there are too many entries, you can use :redir to redirect the
result of map to a register or a file.

**Comment by sadid** [comment]
I double check. The strange thing is it maps to default leader `\` while I've set leader `,` as default leader. Now it's fixed. Thanks
