### ISSUE TITLE
For my setup this plugin replaces the wrong word.

### ISSUE THREAD

**Issue by unphased** [Ron89/thesaurus_query.vim#3]
Depending on the length of the file the plugin replaces a word further above on the file, and certainly not the exact word that is under the cursor.

Since I'm not looking to sacrifice any of my other configuration or plugins at all, I would like to ask for debugging steps and general guidance on how this plugin implements the finding and replacing.

Thanks

**Comment by Ron89** [comment]
Currently recognizing the word is using `expand(<cword>)`, and to replace the word under cursor, I am using `normal wbcw`.[user chosen candidate]. It works fine in my configuration. Could you share with me how it messed up with your configuration? Also, do you have a better solution for word replacing?

**Comment by unphased** [comment]
Thanks for responding!! 

Incidentally I just took a quick dive in the source and yes the offending code is the `normal wbcw` part.

My `b` is bound to page up (i use it in conjunction with the spacebar). Replacing with `normal!` does the job to make it work properly.

**Comment by unphased** [comment]
Would you like a pull request?

**Comment by Ron89** [comment]
Do you think ciw is a better idea? Yes, that'll be nice.

**Comment by unphased** [comment]
i use ciw a lot when I use vim. and naturally I don't use b (I have mapped it to `<BS>`, haha) but either way it's pretty obvious what it's doing... I think making the change be a single character (adding `!`) is the way to go here

**Comment by Ron89** [comment]
Oh, I see, or I can use ! to bypass the mappings. Sorry for the inconvenience caused.

**Comment by unphased** [comment]
Yes I would say either of `normal! wbcw` or `normal! ciw` would be great but anyways ive made the PR
