### ISSUE TITLE
mapping already exists

### ISSUE THREAD

**Issue by alnavv** [Ron89/thesaurus_query.vim#46]
**Full error description:**

Error detected while processing $HOME/.config/nvim/plugged/thesaurus_query.vim/plugin/thesaurus_query.vim:
line   47:
E227: mapping already exists for ,cs

**Solution**:
just comment the problematic <unique> lines in :

thesaurus_query.vim/plugin/thesaurus_query.vim

lines 47,48

**Comment by Ron89** [comment]
just set `g:tq_map_keys` to 0.

**Comment by Ron89** [comment]
Does it solve your issue?

**Comment by Ron89** [comment]
Since no further communication received, I am closing the ticket.

**Comment by yushangakki** [comment]
it works, thanks
