### ISSUE TITLE
<Leader> cs + ^C ---> raise vim error

### ISSUE THREAD

**Issue by petRUShka** [Ron89/thesaurus_query.vim#8]
It is widely used to press `^C` (`Ctrl+C`) for cancellation any command in VIM. When you use `^C` during `thesaurus_query` it is raising following error.

```
Error detected while processing function thesaurus_query#Thesaurus_Query_Lookup:
line   22:
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/home/user/.vim/plugged/thesaurus_query.vim/autoload/thesaurus_query/thesaurus_que
ry.py", line 192, in tq_replace_cursor_word_from_candidates
    thesaurus_user_choice = vim.eval("input('Type number and <Enter> (empty cancels): ')")
KeyboardInterrupt

```

**Comment by Ron89** [comment]
It's a Error_Handler issue. I should be able to fix it by adding 'KeyboardInterrupt' exception handler. Thanks for pointing it out. I'll fix it as soon as I'm free.

**Comment by petRUShka** [comment]
Thanks, now it is working!
